# Use an official Node.js runtime as the base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json for better caching 
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of application code
COPY . .

# Export the port you app listens to 
EXPOSE 8000

# Define the command to run your app
CMD ["npm", "start"]



